### ISSUE TITLE
Support for GamezBD

### ISSUE THREAD

**Issue by Bamboozul** [Sehyn/BDO-FaceTexture-Changer#1]
Hi

Is there a way to add support for **GamezBD client** "Private server"?

The location for the folder is"Documents\GamezBD\FaceTexture", or you can simply give us the ability to choose the location manually.

Thank you very much.

**Comment by Sehyn** [comment]
Hi @MrJktra Thank you for your IDEA,
can you please make the issue here: https://github.com/Sehyn/BDO-Toolbox

As I made a more complete tool.
I will make the ability to load GamezBD FaceTextures once you post your request!

**Comment by Bamboozul** [comment]
> Hi @MrJktra Thank you for your IDEA, can you please make the issue here: https://github.com/Sehyn/BDO-Toolbox
> 
> As I made a more complete tool. I will make the ability to load GamezBD FaceTextures once you post your request!

Sure & btw I downloaded "BDO-Toolbox" but I can't seem to make it work because every time I try to open "BDO-Toolbox.exe" nothing happens and is not running in the task manager either.

**Comment by Sehyn** [comment]
> > Hi @MrJktra Thank you for your IDEA, can you please make the issue here: https://github.com/Sehyn/BDO-Toolbox
> > As I made a more complete tool. I will make the ability to load GamezBD FaceTextures once you post your request!
> 
> Sure & btw I downloaded "BDO-Toolbox" but I can't seem to make it work because every time I try to open "BDO-Toolbox.exe" nothing happens and is not running in the task manager either.

Thank you for pointing this out, I indeed forgot the .dll which loads the theme, it should have been fixed (let me know if this is not the case)
I saw you opened the issue on the Toolbox one, I'll get to work on it now :)
